debugs:
    debug: True 
    showInfResults: False
    dispResults: True

training:
    dataSet: "../datasets/coco_withHand.yaml"
    modelsDir: "../models"
    modelFile: "yolov5nu.yaml"
    #modelFile: "yolov5.yaml"
    weightsDir: "../weights"
    #weightsFile: "yolov5nu.pt" # Pre trained (640px), won't export at 608x608, won't export...
    #weightsFile: "yolov5nu_transferFromCOCO.pt" # Transfer Learing, 81 classes, 640px

    weightsFile: "yolov5nu_tran_hsv_h-1.0_81class.pt"
    weightsFile_tpu: "yolov5nu_tran_hsv_h-1.0_81class_640px_full_integer_quant_edgetpu.tflite"

    transLearn: True
    freezeLayer: 10 # First 10 layers are the backbone (10: freezes 0-9)
    scratchTrain: False #Train from scratch
    # img size should be multiple of 16,
    # Export requires it to be square
    imageSize: [480, 640] #h, w

    #HyperPerams
    epochs: 1

runTime:
    ## Inference Source
    #imgSrc: "directory"
    #imgSrc: "appleHand_hand_4.jpg"
    #imgSrc: "dataset3_310.jpg"
    imgSrc: "camera"
    #imageDir: "../datasets/combinedData/images/val"
    imageDir: "../datasets/testImages"

    #camId: 0 # MAC webcam, laptop built in web cam
    #camId: 1 # Corel TPU, 
    #camId: 2 #laptop USB webcam
    #camId: 3 #
    camId: "rtsp://192.168.1.254:554/s1" # full image
    #camId: "rtsp://192.168.1.254:554/live_mpeg4_1.sdp" # fail
    #camId: "rtsp://192.168.1.254:554/live_h264_1.sdp" # fail
    #camId: "rtsp://192.168.1.254:554/live_h264.sdp" # fail
    #camId: "rtsp://192.168.1.254:554/live_mpeg4.sdp" # fail
    #camId: "rtsp://192.168.1.254:554/live/0/onvif.sdp" # fail
    #camId: "rtsp://192.168.1.254:554/live/0/h264.sdp" # fail
    #camId: "rtsp://192.168.1.254:554/live/0/mpeg4.sdp" # fail
    #camId: "rtsp://192.168.1.254:554/ch0_0.h264" # fail
    #camId: "rtsp://192.168.1.254:554/video.h264" # fail
    #camId: "rtsp://192.168.1.254:554/Streaming/Channels/1" # 
    #camId: "rtsp://192.168.1.254:554/stream" # full image
    #camId: "rtsp://192.168.1.254:554/h264Preview" # 
    #camId: "rtsp://192.168.1.254:554/rtsp_live0" # 
    #camId: "rtsp://192.168.1.254:554/preview" # fail 
    #camId: "rtsp://192.168.1.254:554/live" # fail 
    #camId: "rtsp://192.168.1.254:554/"    #Full image
    camRateHz: 5

    distSettings:
        imagePxlPer_mm: 1.0
        handThreshold: 0.10
        objectThreshold: 0.10
        nmsIouThreshold: 0.80 #only use if iou < this
        #0.6
        handClass: 80

    displaySettings:
        fullScreen: False
        handColor: [0, 255, 0]
        lineColor: [0, 255, 255] # Color in BGR
        objectColor: [0, 0, 255]
        handLineTh: 2 #Thickness in px
        objLineTh: 2
        distLineTh: 2
        runCamOnce: False
