debugs:
    debug: True 
    showInfResults: True
    dispResults: True
    runInfer: True
    saveImages: False

training:
    #Note dataset download directory is '/home/coder/sensorFusion/cv/training/datasets'. You can update this in '/home/coder/.config/Ultralytics/settings.json'
    # Should be: '/home/coder/sensorFusion/cv/datasets'
    dataSetDir: "../datasets"
    #dataSet: "../datasets/appleHand.yaml"
    #dataSet: "ExoGlove.v2-in-progess-25-03-06/data.yaml" #Day 2 part train I ~ 1k images
    dataSet: "day2_partIII_TopCamFullyLab/data.yaml"
    #dataSet: "day2_partII_2138Images/data.yaml"
    #dataSet: "../datasets/coco_withHand.yaml"
    #dataSet: "../datasets/coco_7Class.yaml"
    modelsDir: "../models"
    weightsDir: "../weights"

    #modelFile: "yolov5nu.yaml"
    #weightsForTransfer: "yolov5nu.pt"
    #weightsFile: "yolov5nu_tran_hsv_h-1.0_2class.pt"
    #weightsFile: "yolov5nu_tran_hsv_h-1.0_7class.pt"
    #weightsFile: "yolov5nu_transferFromCOCO.pt" # Transfer Learing, 81 classes, 640px
    #weightsFile_tpu: "yolov5nu_tran_hsv_h-1.0_81class_640px_full_integer_quant_edgetpu.tflite"
    #weightsFile_tpu: "yolov8n_tran_2class_full_integer_quant_edgetpu.tflite"
    #weightsFile_tpu: "yolo11n_tran_2class_full_integer_quant_edgetpu.tflite"
    weightsFile_tpu: "yolo8_19_UL-New_day2_fullLabTopCam_60epochs.tflite"

    modelFile: "yolov8n.yaml"
    weightsForTransfer: "yolov8n.pt"
    weightsFile: "yolo8_19_UL-New_day2_fullLabTopCam_60epochs.pt"
    #weightsFile: "yolov8n_newDataset_inProgessII.pt"

    # Will not run on TPU
    #modelFile: "yolo11n.yaml"
    #weightsForTransfer: "yolo11n.pt"
    #weightsFile: "yolo11n_tran_2class.pt"


    transLearn: True
    freezeLayer: 11 # First 10 layers are the backbone (10: freezes 0-9)
    #scratchTrain: False #Train from scratch
    # img size should be multiple of 16,
    # Export requires it to be square
    imageSize: [480, 640] #h, w

    #HyperPerams
    epochs: 60

runTime:
    ## Inference Source
    #imageDir: "../datasets/combinedData/images/val"
    #imageDir: "../datasets/testImages"
    #imageDir: "../images/fo"
    #imageDir: "../images/test_day2"
    #imageDir: "/Volumes/Data/exoGlove/images_capture/day1" # On Mac
    imageDir: "../images_capture/day1" # On Mac
    #imageDir: "../images_capture/test_day2/cam-1_overhead/tape_spool/sub3"
    #imageDir: "/Volumes/Data/exoGlove/images_capture/test_day2/cam-1_overhead/apple/sub3"
    #imgSrc: "appleHand_hand_4.jpg"
    #imgSrc: "dataset3_310.jpg"
    imgSrc: "camera"
    #imgSrc: "*_apple_*"
    #imgSrc: "*_lid*"
    #imgSrc: "*_spoon_*"
    #imgSrc: "*"
    #imgSrc: "1_20241121-130802-434_4_apple_2.jpg"

    nCameras: 1
    focus: 15  #inc of 5, 0-255, negitive for auto
    camId: 2
    #camId: 0 # MAC webcam, laptop built in web cam
    #camId: 1 # Corel TPU, 
    #camId: 2 #laptop USB webcam
    #camId: 3 #
    #camId: "rtsp://192.168.1.254:554/s1" # full image
    #camId: "rtsp://192.168.1.254:554/"    #Full image
    #camId_2: 0 # MAC webcam, laptop built in web cam
    camId_2: "rtsp://192.168.1.254:554/"    #Full image
    camRateHz: 5

    distSettings:
        imagePxlPer_mm: .51 #From cv/pxDistCalc.ods
        handThreshold: 0.50
        objectThreshold: 0.60
        nmsIouThreshold: 0.90 #only use if iou < this
        handClass: 4

    displaySettings:
        fullScreen: False
        handLineTh: 2 #Thickness in px
        objLineTh: 2
        distLineTh: 2
        runCamOnce: False
timeSync:
    gpio_chip: 4
    gpio_pin : 13

servos:
    i2c:
        port: "/dev/i2c-1"
        device: 0x40
        #if you are slow, set the clock faster
        #clock_MHz: 26.25 #Suposed to be 25, but seems fast, by a lot!
        clock_MHz: 26.4 #also veries a lot with temp

    servos: 
        pwm_Hz: 50
        leavRunning: False

comms:
    # None to not use
    port: "None" # TPU
    #port: "/dev/ttyUSB0" # Linux
    #port: "/dev/tty.SLAB_USBtoUART" # Mac
    speed: 115200
    dataBits: 8
    stobBits: 1
    parity: 'N'
    id: "CV"
