debugs:
    debug: True 
    showInfResults: False
    dispResults: True
    runInfer: True
    saveImages: False

training:
    dataSet: "../datasets/coco_withHand.yaml"
    #dataSet: "../datasets/coco_7Class.yaml"
    modelsDir: "../models"
    weightsDir: "../weights"

    modelFile: "yolov5nu.yaml"
    weightsForTransfer: "yolov5nu.pt"
    weightsFile: "yolov5nu_tran_hsv_h-1.0_2class.pt"
    #weightsFile: "yolov5nu_tran_hsv_h-1.0_7class.pt"
    weightsFile: "yolov5nu_transferFromCOCO.pt" # Transfer Learing, 81 classes, 640px
    #weightsFile_tpu: "yolov5nu_tran_hsv_h-1.0_81class_640px_full_integer_quant_edgetpu.tflite"
    weightsFile_tpu: "yolov8n_tran_2class_full_integer_quant_edgetpu.tflite"
    #weightsFile_tpu: "yolo11n_tran_2class_full_integer_quant_edgetpu.tflite"

    #modelFile: "yolov8n.yaml"
    #weightsForTransfer: "yolov8n.pt"
    #weightsFile: "yolov8n_tran_2class.pt"

    #modelFile: "yolo11n.yaml"
    #weightsForTransfer: "yolo11n.pt"
    #weightsFile: "yolo11n_tran_2class.pt"


    transLearn: True
    freezeLayer: 11 # First 10 layers are the backbone (10: freezes 0-9)
    scratchTrain: False #Train from scratch
    # img size should be multiple of 16,
    # Export requires it to be square
    imageSize: [480, 640] #h, w

    #HyperPerams
    epochs: 300

runTime:
    ## Inference Source
    #imgSrc: "directory"
    #imgSrc: "appleHand_hand_4.jpg"
    #imgSrc: "dataset3_310.jpg"
    imgSrc: "camera"
    #imageDir: "../datasets/combinedData/images/val"
    #imageDir: "../datasets/testImages"
    imageDir: "../datasets/bar"

    nCameras: 2
    camId: 0 # MAC webcam, laptop built in web cam
    #camId: 1 # Corel TPU, 
    #camId: 2 #laptop USB webcam
    #camId: 3 #
    #camId: "rtsp://192.168.1.254:554/s1" # full image
    #camId: "rtsp://192.168.1.254:554/"    #Full image
    camId_2: 2 # MAC webcam, laptop built in web cam
    camRateHz: 5

    distSettings:
        imagePxlPer_mm: 1.0
        handThreshold: 0.50
        objectThreshold: 0.60
        nmsIouThreshold: 0.90 #only use if iou < this
        #0.6
        handClass: 80

    displaySettings:
        fullScreen: False
        handColor: [0, 255, 0]
        lineColor: [0, 255, 255] # Color in BGR
        objectColor: [0, 0, 255]
        handLineTh: 2 #Thickness in px
        objLineTh: 2
        distLineTh: 2
        runCamOnce: False

servos:
    i2c:
        port: "/dev/i2c-1"
        device: 0x40
        #if you are slow, set the clock faster
        #clock_MHz: 26.25 #Suposed to be 25, but seems fast, by a lot!
        clock_MHz: 26.4 #also veries a lot with temp

    servos: 
        pwm_Hz: 50
        leavRunning: False
