debugs:
    debug: True 
    showInfResults: False
    dispResults: True

training:
    dataSet: "../datasets/coco_withHand.yaml"
    weightsDir: "../weights"
    #weightsFile: "yolov5nu.pt" # Pre trained (640px), won't export at 608x608, won't export...
    #weightsFile: "yolov5nu_transferFromCOCO.pt" # Transfer Learing, 81 classes, 640px
    weightsFile: "yolov5nu_tran_hsv_h-1.0_81class.pt"
    weightsFile_tpu: "yolov5nu_tran_hsv_h-1.0_81class_608_full_integer_quant_edgetpu.tflite"

    # img size should be multiple of 16,
    # Export requires it to be square
    #imageSize: [240, 320] #h, w
    #imageSize: [480, 640] #h, w
    imageSize: [480, 480] #h, w
    #imageSize: [608, 608] #h, w: Largest export (ram limited?)

runTime:
    ## Inference Source
    #imgSrc: "directory"
    imgSrc: "appleHand_hand_4.jpg"
    #imgSrc: "webCam"
    #imageDir: "../datasets/combinedData/images/val"
    imageDir: "../datasets/testImages"

    camId: 0 # MAC webcam, laptop built in web cam
    #camId: 1 # Corel TPU, 
    #camId: 2 #laptop USB webcam
    #camId: 3 #
    camRateHz: 5

    distSettings:
        imagePxlPer_mm: 1.0
        handThreshold: 0.6
        objectThreshold: 0.2
        #0.6
        handClass: 80

    displaySettings:
        fullScreen: False
        handColor: [0, 255, 0]
        lineColor: [125, 125, 125] # Color in BGR
        objectColor: [0, 0, 255]
        handLineTh: 2 #Thickness in px
        objLineTh: 2
        distLineTh: 1
        runCamOnce: False
